#!/bin/bash

FILENAME="AZTEC"
DISKNAME="aztec PRODOS (san inc crack)(4cade compatible).po"

FILENAME="PR"
DISKNAME="res/dsk/pharaoh's revenge PRODOS (san inc pack).po"
git checkout res/ACTION.HGR.UNCOMPRESSED/"$FILENAME"
git checkout res/ACTION.HGR/"$FILENAME"
git checkout res/ARTWORK.SHR.SCORES/"$FILENAME"
git checkout res/ARTWORK.SHR.UNCOMPRESSED/"$FILENAME"
git checkout res/ARTWORK.SHR/"$FILENAME"
git checkout res/ATTRACT/"$FILENAME"
git checkout res/GAMEHELP/"$FILENAME"
git checkout res/TITLE.HGR.UNPACKED/"$FILENAME"
git checkout res/TITLE.HGR/"$FILENAME"
git checkout src/demo/"$echo"${FILENAME,,}".a"
git checkout res/dsk/"$DISKNAME"


FILENAME="KARATEKA"
DISKNAME=".po"
git checkout res/ACTION.HGR.UNCOMPRESSED/"$FILENAME"
git checkout res/ACTION.HGR/"$FILENAME"
git checkout res/ARTWORK.SHR.SCORES/"$FILENAME"
git checkout res/ARTWORK.SHR.UNCOMPRESSED/"$FILENAME"
git checkout res/ARTWORK.SHR/"$FILENAME"
git checkout res/ATTRACT/"$FILENAME"
git checkout res/GAMEHELP/"$FILENAME"
git checkout res/TITLE.HGR.UNPACKED/"$FILENAME"
git checkout res/TITLE.HGR/"$FILENAME"
git checkout src/demo/"$echo"${FILENAME,,}".a"
git checkout res/dsk/"$DISKNAME"
FILENAME="MINER.II"
DISKNAME=".po"
git checkout res/ACTION.HGR.UNCOMPRESSED/"$FILENAME"
git checkout res/ACTION.HGR/"$FILENAME"
git checkout res/ARTWORK.SHR.SCORES/"$FILENAME"
git checkout res/ARTWORK.SHR.UNCOMPRESSED/"$FILENAME"
git checkout res/ARTWORK.SHR/"$FILENAME"
git checkout res/ATTRACT/"$FILENAME"
git checkout res/GAMEHELP/"$FILENAME"
git checkout res/TITLE.HGR.UNPACKED/"$FILENAME"
git checkout res/TITLE.HGR/"$FILENAME"
git checkout src/demo/"$echo"${FILENAME,,}".a"
git checkout res/dsk/"$DISKNAME"

FILENAME="MOON.PATROL"
DISKNAME="moon patrol 18k file PRODOS (san inc crack).po"
git checkout res/ACTION.HGR.UNCOMPRESSED/"$FILENAME"
git checkout res/ACTION.HGR/"$FILENAME"
git checkout res/ARTWORK.SHR.SCORES/"$FILENAME"
git checkout res/ARTWORK.SHR.UNCOMPRESSED/"$FILENAME"
git checkout res/ARTWORK.SHR/"$FILENAME"
git checkout res/ATTRACT/"$FILENAME"
git checkout res/GAMEHELP/"$FILENAME"
git checkout res/TITLE.HGR.UNPACKED/"$FILENAME"
git checkout res/TITLE.HGR/"$FILENAME"
git checkout src/demo/"$echo"${FILENAME,,}".a"
git checkout res/dsk/"$DISKNAME"


FILENAME="MP"
DISKNAME="ms. pacman 12k file PRODOS (san inc pack).po"
git checkout res/ACTION.HGR.UNCOMPRESSED/"$FILENAME"
git checkout res/ACTION.HGR/"$FILENAME"
git checkout res/ARTWORK.SHR.SCORES/"$FILENAME"
git checkout res/ARTWORK.SHR.UNCOMPRESSED/"$FILENAME"
git checkout res/ARTWORK.SHR/"$FILENAME"
git checkout res/ATTRACT/"$FILENAME"
git checkout res/GAMEHELP/"$FILENAME"
git checkout res/TITLE.HGR.UNPACKED/"$FILENAME"
git checkout res/TITLE.HGR/"$FILENAME"
git checkout src/demo/"$echo"${FILENAME,,}".a"
git checkout res/dsk/"$DISKNAME"

FILENAME="PACMAN"
DISKNAME="pacman (Atari) 14k file PRODOS (san inc pack).po"
git checkout res/ACTION.HGR.UNCOMPRESSED/"$FILENAME"
git checkout res/ACTION.HGR/"$FILENAME"
git checkout res/ARTWORK.SHR.SCORES/"$FILENAME"
git checkout res/ARTWORK.SHR.UNCOMPRESSED/"$FILENAME"
git checkout res/ARTWORK.SHR/"$FILENAME"
git checkout res/ATTRACT/"$FILENAME"
git checkout res/GAMEHELP/"$FILENAME"
git checkout res/TITLE.HGR.UNPACKED/"$FILENAME"
git checkout res/TITLE.HGR/"$FILENAME"
git checkout src/demo/"$echo"${FILENAME,,}".a"
git checkout res/dsk/"$DISKNAME"

FILENAME="PITFALL.II"
DISKNAME="pitfall II 14k file PRODOS (san inc crack).po"
git checkout res/ACTION.HGR.UNCOMPRESSED/"$FILENAME"
git checkout res/ACTION.HGR/"$FILENAME"
git checkout res/ARTWORK.SHR.SCORES/"$FILENAME"
git checkout res/ARTWORK.SHR.UNCOMPRESSED/"$FILENAME"
git checkout res/ARTWORK.SHR/"$FILENAME"
git checkout res/ATTRACT/"$FILENAME"
git checkout res/GAMEHELP/"$FILENAME"
git checkout res/TITLE.HGR.UNPACKED/"$FILENAME"
git checkout res/TITLE.HGR/"$FILENAME"
git checkout src/demo/"$echo"${FILENAME,,}".a"
git checkout res/dsk/"$DISKNAME"


FILENAME="ROBOTRON.2084"
DISKNAME="robotron 2084 13k file PRODOS (san inc pack).po"
git checkout res/ACTION.HGR.UNCOMPRESSED/"$FILENAME"
git checkout res/ACTION.HGR/"$FILENAME"
git checkout res/ARTWORK.SHR.SCORES/"$FILENAME"
git checkout res/ARTWORK.SHR.UNCOMPRESSED/"$FILENAME"
git checkout res/ARTWORK.SHR/"$FILENAME"
git checkout res/ATTRACT/"$FILENAME"
git checkout res/GAMEHELP/"$FILENAME"
git checkout res/TITLE.HGR.UNPACKED/"$FILENAME"
git checkout res/TITLE.HGR/"$FILENAME"
git checkout src/demo/"$echo"${FILENAME,,}".a"
git checkout res/dsk/"$DISKNAME"


FILENAME="STARGATE"
DISKNAME="stargate 16k file PRODOS (san inc pack).po"
git checkout res/ACTION.HGR.UNCOMPRESSED/"$FILENAME"
git checkout res/ACTION.HGR/"$FILENAME"
git checkout res/ARTWORK.SHR.SCORES/"$FILENAME"
git checkout res/ARTWORK.SHR.UNCOMPRESSED/"$FILENAME"
git checkout res/ARTWORK.SHR/"$FILENAME"
git checkout res/ATTRACT/"$FILENAME"
git checkout res/GAMEHELP/"$FILENAME"
git checkout res/TITLE.HGR.UNPACKED/"$FILENAME"
git checkout res/TITLE.HGR/"$FILENAME"
git checkout src/demo/"$echo"${FILENAME,,}".a"
git checkout res/dsk/"$DISKNAME"



exit (0)



# Set the filename variable
FILENAME="CHOPLIFTER"
DISKNAME="choplifter 17k file PRODOS (san inc crack).po"
git checkout res/ACTION.HGR.UNCOMPRESSED/"$FILENAME"
git checkout res/ACTION.HGR/"$FILENAME"
git checkout res/ARTWORK.SHR.SCORES/"$FILENAME"
git checkout res/ARTWORK.SHR.UNCOMPRESSED/"$FILENAME"
git checkout res/ARTWORK.SHR/"$FILENAME"
git checkout res/ATTRACT/"$FILENAME"
git checkout res/GAMEHELP/"$FILENAME"
git checkout res/TITLE.HGR.UNPACKED/"$FILENAME"
git checkout res/TITLE.HGR/"$FILENAME"
git checkout src/demo/"$echo"${FILENAME,,}".a"
git checkout res/dsk/"$DISKNAME"
# Set the filename variable
FILENAME="CONAN"
DISKNAME="conan 1-side bugfix PRODOS (san inc pack).po"
git checkout res/ACTION.HGR.UNCOMPRESSED/"$FILENAME"
git checkout res/ACTION.HGR/"$FILENAME"
git checkout res/ARTWORK.SHR.SCORES/"$FILENAME"
git checkout res/ARTWORK.SHR.UNCOMPRESSED/"$FILENAME"
git checkout res/ARTWORK.SHR/"$FILENAME"
git checkout res/ATTRACT/"$FILENAME"
git checkout res/GAMEHELP/"$FILENAME"
git checkout res/TITLE.HGR.UNPACKED/"$FILENAME"
git checkout res/TITLE.HGR/"$FILENAME"
git checkout src/demo/"$echo"${FILENAME,,}".a"
git checkout res/dsk/"$DISKNAME"
# Set the filename variable
FILENAME="DEFENDER"
DISKNAME="defender 9k file PRODOS (san inc pack).po"
git checkout res/ACTION.HGR.UNCOMPRESSED/"$FILENAME"
git checkout res/ACTION.HGR/"$FILENAME"
git checkout res/ARTWORK.SHR.SCORES/"$FILENAME"
git checkout res/ARTWORK.SHR.UNCOMPRESSED/"$FILENAME"
git checkout res/ARTWORK.SHR/"$FILENAME"
git checkout res/ATTRACT/"$FILENAME"
git checkout res/GAMEHELP/"$FILENAME"
git checkout res/TITLE.HGR.UNPACKED/"$FILENAME"
git checkout res/TITLE.HGR/"$FILENAME"
git checkout src/demo/"$echo"${FILENAME,,}".a"
git checkout res/dsk/"$DISKNAME"
# Set the filename variable
FILENAME="DIG.DUG*"
DISKNAME="dig dug 13k file PRODOS (san inc pack).po"
git checkout res/ACTION.HGR.UNCOMPRESSED/"$FILENAME"
git checkout res/ACTION.HGR/"$FILENAME"
git checkout res/ARTWORK.SHR.SCORES/"$FILENAME"
git checkout res/ARTWORK.SHR.UNCOMPRESSED/"$FILENAME"
git checkout res/ARTWORK.SHR/"$FILENAME"
git checkout res/ATTRACT/"$FILENAME"
git checkout res/GAMEHELP/"$FILENAME"
git checkout res/TITLE.HGR.UNPACKED/"$FILENAME"
git checkout res/TITLE.HGR/"$FILENAME"
git checkout src/demo/"$echo"${FILENAME,,}".a"
git checkout res/dsk/"$DISKNAME"
# Set the filename variable
FILENAME="GALAXIAN"
DISKNAME="galaxian 10k file PRODOS (san inc pack).po"
git checkout res/ACTION.HGR.UNCOMPRESSED/"$FILENAME"
git checkout res/ACTION.HGR/"$FILENAME"
git checkout res/ARTWORK.SHR.SCORES/"$FILENAME"
git checkout res/ARTWORK.SHR.UNCOMPRESSED/"$FILENAME"
git checkout res/ARTWORK.SHR/"$FILENAME"
git checkout res/ATTRACT/"$FILENAME"
git checkout res/GAMEHELP/"$FILENAME"
git checkout res/TITLE.HGR.UNPACKED/"$FILENAME"
git checkout res/TITLE.HGR/"$FILENAME"
git checkout src/demo/"$echo"${FILENAME,,}".a"
git checkout res/dsk/"$DISKNAME"



FILENAME="GHOSTBUSTERS"
DISKNAME="ghostbusters PRODOS (san inc pack).po"
git checkout res/ACTION.HGR.UNCOMPRESSED/"$FILENAME"
git checkout res/ACTION.HGR/"$FILENAME"
git checkout res/ARTWORK.SHR.SCORES/"$FILENAME"
git checkout res/ARTWORK.SHR.UNCOMPRESSED/"$FILENAME"
git checkout res/ARTWORK.SHR/"$FILENAME"
git checkout res/ATTRACT/"$FILENAME"
git checkout res/GAMEHELP/"$FILENAME"
git checkout res/TITLE.HGR.UNPACKED/"$FILENAME"
git checkout res/TITLE.HGR/"$FILENAME"
git checkout src/demo/"$echo"${FILENAME,,}".a"
git checkout res/dsk/"$DISKNAME"



FILENAME="HARD.HAT.MACK"
DISKNAME="hard hat mack 19k file PRODOS (san inc crack).po"
git checkout res/ACTION.HGR.UNCOMPRESSED/"$FILENAME"
git checkout res/ACTION.HGR/"$FILENAME"
git checkout res/ARTWORK.SHR.SCORES/"$FILENAME"
git checkout res/ARTWORK.SHR.UNCOMPRESSED/"$FILENAME"
git checkout res/ARTWORK.SHR/"$FILENAME"
git checkout res/ATTRACT/"$FILENAME"
git checkout res/GAMEHELP/"$FILENAME"
git checkout res/TITLE.HGR.UNPACKED/"$FILENAME"
git checkout res/TITLE.HGR/"$FILENAME"
git checkout src/demo/"$echo"${FILENAME,,}".a"
git checkout res/dsk/"$DISKNAME"

FILENAME="JOUST"
DISKNAME="joust 26k file PRODOS (san inc pack).po"
git checkout res/ACTION.HGR.UNCOMPRESSED/"$FILENAME"
git checkout res/ACTION.HGR/"$FILENAME"
git checkout res/ARTWORK.SHR.SCORES/"$FILENAME"
git checkout res/ARTWORK.SHR.UNCOMPRESSED/"$FILENAME"
git checkout res/ARTWORK.SHR/"$FILENAME"
git checkout res/ATTRACT/"$FILENAME"
git checkout res/GAMEHELP/"$FILENAME"
git checkout res/TITLE.HGR.UNPACKED/"$FILENAME"
git checkout res/TITLE.HGR/"$FILENAME"
git checkout src/demo/"$echo"${FILENAME,,}".a"
git checkout res/dsk/"$DISKNAME"


exit(0)

FILENAME="TIME.TUNNELS"
DISKNAME="res/dsk/time tunnels 12k file PRODOS (san inc pack).po"
git checkout res/ACTION.HGR.UNCOMPRESSED/"$FILENAME"
git checkout res/ACTION.HGR/"$FILENAME"
git checkout res/ARTWORK.SHR.SCORES/"$FILENAME"
git checkout res/ARTWORK.SHR.UNCOMPRESSED/"$FILENAME"
git checkout res/ARTWORK.SHR/"$FILENAME"
git checkout res/ATTRACT/"$FILENAME"
git checkout res/GAMEHELP/"$FILENAME"
git checkout res/TITLE.HGR.UNPACKED/"$FILENAME"
git checkout res/TITLE.HGR/"$FILENAME"
git checkout res/dsk/"$DISKNAME"
FILENAME=""
DISKNAME=".po"
git checkout res/ACTION.HGR.UNCOMPRESSED/"$FILENAME"
git checkout res/ACTION.HGR/"$FILENAME"
git checkout res/ARTWORK.SHR.SCORES/"$FILENAME"
git checkout res/ARTWORK.SHR.UNCOMPRESSED/"$FILENAME"
git checkout res/ARTWORK.SHR/"$FILENAME"
git checkout res/ATTRACT/"$FILENAME"
git checkout res/GAMEHELP/"$FILENAME"
git checkout res/TITLE.HGR.UNPACKED/"$FILENAME"
git checkout res/TITLE.HGR/"$FILENAME"
git checkout src/demo/"$echo"${FILENAME,,}".a"
git checkout res/dsk/"$DISKNAME"
FILENAME=""
DISKNAME=".po"
git checkout res/ACTION.HGR.UNCOMPRESSED/"$FILENAME"
git checkout res/ACTION.HGR/"$FILENAME"
git checkout res/ARTWORK.SHR.SCORES/"$FILENAME"
git checkout res/ARTWORK.SHR.UNCOMPRESSED/"$FILENAME"
git checkout res/ARTWORK.SHR/"$FILENAME"
git checkout res/ATTRACT/"$FILENAME"
git checkout res/GAMEHELP/"$FILENAME"
git checkout res/TITLE.HGR.UNPACKED/"$FILENAME"
git checkout res/TITLE.HGR/"$FILENAME"
git checkout src/demo/"$echo"${FILENAME,,}".a"
git checkout res/dsk/"$DISKNAME"


# Set the filename variable
FILENAME="APPLE.PANIC"
DISKNAME="apple panic 12k file PRODOS (san inc pack).po"
git checkout res/ACTION.HGR.UNCOMPRESSED/"$FILENAME"
git checkout res/ACTION.HGR/"$FILENAME"
git checkout res/ARTWORK.SHR.SCORES/"$FILENAME"
git checkout res/ARTWORK.SHR.UNCOMPRESSED/"$FILENAME"
git checkout res/ARTWORK.SHR/"$FILENAME"
git checkout res/ATTRACT/"$FILENAME"
git checkout res/GAMEHELP/"$FILENAME"
git checkout res/TITLE.HGR.UNPACKED/"$FILENAME"
git checkout res/TITLE.HGR/"$FILENAME"
git checkout src/demo/"$echo"${FILENAME,,}".a"
git checkout res/dsk/"$DISKNAME"

FILENAME="BATTLEZONE"
DISKNAME="battlezone 17k file PRODOS (san inc pack).po"
git checkout res/ACTION.HGR.UNCOMPRESSED/"$FILENAME"
git checkout res/ACTION.HGR/"$FILENAME"
git checkout res/ARTWORK.SHR.SCORES/"$FILENAME"
git checkout res/ARTWORK.SHR.UNCOMPRESSED/"$FILENAME"
git checkout res/ARTWORK.SHR/"$FILENAME"
git checkout res/ATTRACT/"$FILENAME"
git checkout res/GAMEHELP/"$FILENAME"
git checkout res/TITLE.HGR.UNPACKED/"$FILENAME"
git checkout res/TITLE.HGR/"$FILENAME"
git checkout src/demo/"$echo"${FILENAME,,}".a"
git checkout res/dsk/"$DISKNAME"

centi
FILENAME="CENTIPEDE"
DISKNAME="centipede 6k file PRODOS (san inc crack).po"
git checkout res/ACTION.HGR.UNCOMPRESSED/"$FILENAME"
git checkout res/ACTION.HGR/"$FILENAME"
git checkout res/ARTWORK.SHR.SCORES/"$FILENAME"
git checkout res/ARTWORK.SHR.UNCOMPRESSED/"$FILENAME"
git checkout res/ARTWORK.SHR/"$FILENAME"
git checkout res/ATTRACT/"$FILENAME"
git checkout res/GAMEHELP/"$FILENAME"
git checkout res/TITLE.HGR.UNPACKED/"$FILENAME"
git checkout res/TITLE.HGR/"$FILENAME"
git checkout src/demo/"$echo"${FILENAME,,}".a"
git checkout res/dsk/"$DISKNAME"



FILENAME="CW"
DISKNAME="castle wolfenstein 1984 PRODOS (san inc pack).po"
git checkout res/ACTION.HGR.UNCOMPRESSED/"$FILENAME"
git checkout res/ACTION.HGR/"$FILENAME"
git checkout res/ARTWORK.SHR.SCORES/"$FILENAME"
git checkout res/ARTWORK.SHR.UNCOMPRESSED/"$FILENAME"
git checkout res/ARTWORK.SHR/"$FILENAME"
git checkout res/ATTRACT/"$FILENAME"
git checkout res/GAMEHELP/"$FILENAME"
git checkout res/TITLE.HGR.UNPACKED/"$FILENAME"
git checkout res/TITLE.HGR/"$FILENAME"
git checkout src/demo/"$echo"${FILENAME,,}".a"
git checkout res/dsk/"$DISKNAME"





exit(0)


# Set the filename variable
FILENAME="PACMAN"
DISKNAME="pacman (Atari) 14k file PRODOS (san inc pack).po"
git checkout res/ACTION.HGR.UNCOMPRESSED/"$FILENAME"
git checkout res/ACTION.HGR/"$FILENAME"
git checkout res/ARTWORK.SHR.SCORES/"$FILENAME"
git checkout res/ARTWORK.SHR.UNCOMPRESSED/"$FILENAME"
git checkout res/ARTWORK.SHR/"$FILENAME"
git checkout res/ATTRACT/"$FILENAME"
git checkout res/GAMEHELP/"$FILENAME"
git checkout res/TITLE.HGR.UNPACKED/"$FILENAME"
git checkout res/TITLE.HGR/"$FILENAME"
git checkout res/dsk/"$DISKNAME"

FILENAME="MP"
DISKNAME="ms. pacman 12k file PRODOS (san inc pack).po"
git checkout res/ACTION.HGR.UNCOMPRESSED/"$FILENAME"
git checkout res/ACTION.HGR/"$FILENAME"
git checkout res/ARTWORK.SHR.SCORES/"$FILENAME"
git checkout res/ARTWORK.SHR.UNCOMPRESSED/"$FILENAME"
git checkout res/ARTWORK.SHR/"$FILENAME"
git checkout res/ATTRACT/"$FILENAME"
git checkout res/GAMEHELP/"$FILENAME"
git checkout res/TITLE.HGR.UNPACKED/"$FILENAME"
git checkout res/TITLE.HGR/"$FILENAME"
git checkout res/dsk/"$DISKNAME"

FILENAME="MOON.PATROL"
DISKNAME="moon patrol 18k file PRODOS (san inc crack).po"
git checkout res/ACTION.HGR.UNCOMPRESSED/"$FILENAME"
git checkout res/ACTION.HGR/"$FILENAME"
git checkout res/ARTWORK.SHR.SCORES/"$FILENAME"
git checkout res/ARTWORK.SHR.UNCOMPRESSED/"$FILENAME"
git checkout res/ARTWORK.SHR/"$FILENAME"
git checkout res/ATTRACT/"$FILENAME"
git checkout res/GAMEHELP/"$FILENAME"
git checkout res/TITLE.HGR.UNPACKED/"$FILENAME"
git checkout res/TITLE.HGR/"$FILENAME"
git checkout res/dsk/"$DISKNAME"


FILENAME="ROBOTRON.2084"
DISKNAME="robotron 2084 13k file PRODOS (san inc pack).po"
git checkout res/ACTION.HGR.UNCOMPRESSED/"$FILENAME"
git checkout res/ACTION.HGR/"$FILENAME"
git checkout res/ARTWORK.SHR.SCORES/"$FILENAME"
git checkout res/ARTWORK.SHR.UNCOMPRESSED/"$FILENAME"
git checkout res/ARTWORK.SHR/"$FILENAME"
git checkout res/ATTRACT/"$FILENAME"
git checkout res/GAMEHELP/"$FILENAME"
git checkout res/TITLE.HGR.UNPACKED/"$FILENAME"
git checkout res/TITLE.HGR/"$FILENAME"
git checkout res/dsk/"$DISKNAME"

FILENAME="BATTLEZONE"
DISKNAME="battlezone 17k file PRODOS (san inc pack).po"
git checkout res/ACTION.HGR.UNCOMPRESSED/"$FILENAME"
git checkout res/ACTION.HGR/"$FILENAME"
git checkout res/ARTWORK.SHR.SCORES/"$FILENAME"
git checkout res/ARTWORK.SHR.UNCOMPRESSED/"$FILENAME"
git checkout res/ARTWORK.SHR/"$FILENAME"
git checkout res/ATTRACT/"$FILENAME"
git checkout res/GAMEHELP/"$FILENAME"
git checkout res/TITLE.HGR.UNPACKED/"$FILENAME"
git checkout res/TITLE.HGR/"$FILENAME"
git checkout res/dsk/"$DISKNAME"


FILENAME="H.E.R.O"
DISKNAME="res/dsk/hero 12k file PRODOS (san inc pack) (fixes refresh bug in original game).po"
git checkout res/ACTION.HGR.UNCOMPRESSED/"$FILENAME"
git checkout res/ACTION.HGR/"$FILENAME"
git checkout res/ARTWORK.SHR.SCORES/"$FILENAME"
git checkout res/ARTWORK.SHR.UNCOMPRESSED/"$FILENAME"
git checkout res/ARTWORK.SHR/"$FILENAME"
git checkout res/ATTRACT/"$FILENAME"
git checkout res/GAMEHELP/"$FILENAME"
git checkout res/TITLE.HGR.UNPACKED/"$FILENAME"
git checkout res/TITLE.HGR/"$FILENAME"
git checkout res/dsk/"$DISKNAME"



FILENAME="DONKEY.KONG"
DISKNAME="donkey kong PRODOS (san inc pack).po"
git checkout res/ACTION.HGR.UNCOMPRESSED/"$FILENAME"
git checkout res/ACTION.HGR/"$FILENAME"
git checkout res/ARTWORK.SHR.SCORES/"$FILENAME"
git checkout res/ARTWORK.SHR.UNCOMPRESSED/"$FILENAME"
git checkout res/ARTWORK.SHR/"$FILENAME"
git checkout res/ATTRACT/"$FILENAME"
git checkout res/GAMEHELP/"$FILENAME"
git checkout res/TITLE.HGR.UNPACKED/"$FILENAME"
git checkout res/TITLE.HGR/"$FILENAME"
git checkout res/dsk/"$DISKNAME"


FILENAME="GALAXIAN"
DISKNAME="galaxian 10k file PRODOS (san inc pack).po"
git checkout res/ACTION.HGR.UNCOMPRESSED/"$FILENAME"
git checkout res/ACTION.HGR/"$FILENAME"
git checkout res/ARTWORK.SHR.SCORES/"$FILENAME"
git checkout res/ARTWORK.SHR.UNCOMPRESSED/"$FILENAME"
git checkout res/ARTWORK.SHR/"$FILENAME"
git checkout res/ATTRACT/"$FILENAME"
git checkout res/GAMEHELP/"$FILENAME"
git checkout res/TITLE.HGR.UNPACKED/"$FILENAME"
git checkout res/TITLE.HGR/"$FILENAME"
git checkout res/dsk/"$DISKNAME"

FILENAME="JOUST"
DISKNAME="joust 26k file PRODOS (san inc pack).po"
git checkout res/ACTION.HGR.UNCOMPRESSED/"$FILENAME"
git checkout res/ACTION.HGR/"$FILENAME"
git checkout res/ARTWORK.SHR.SCORES/"$FILENAME"
git checkout res/ARTWORK.SHR.UNCOMPRESSED/"$FILENAME"
git checkout res/ARTWORK.SHR/"$FILENAME"
git checkout res/ATTRACT/"$FILENAME"
git checkout res/GAMEHELP/"$FILENAME"
git checkout res/TITLE.HGR.UNPACKED/"$FILENAME"
git checkout res/TITLE.HGR/"$FILENAME"
git checkout res/dsk/"$DISKNAME"

FILENAME="DIG.DUG*"
DISKNAME="dig dug 13k file PRODOS (san inc pack).po"
git checkout res/ACTION.HGR.UNCOMPRESSED/"$FILENAME"
git checkout res/ACTION.HGR/"$FILENAME"
git checkout res/ARTWORK.SHR.SCORES/"$FILENAME"
git checkout res/ARTWORK.SHR.UNCOMPRESSED/"$FILENAME"
git checkout res/ARTWORK.SHR/"$FILENAME"
git checkout res/ATTRACT/"$FILENAME"
git checkout res/GAMEHELP/"$FILENAME"
git checkout res/TITLE.HGR.UNPACKED/"$FILENAME"
git checkout res/TITLE.HGR/"$FILENAME"
git checkout res/dsk/"$DISKNAME"


FILENAME="CW"
DISKNAME="castle wolfenstein 1984 PRODOS (san inc pack).po"
git checkout res/ACTION.HGR.UNCOMPRESSED/"$FILENAME"
git checkout res/ACTION.HGR/"$FILENAME"
git checkout res/ARTWORK.SHR.SCORES/"$FILENAME"
git checkout res/ARTWORK.SHR.UNCOMPRESSED/"$FILENAME"
git checkout res/ARTWORK.SHR/"$FILENAME"
git checkout res/ATTRACT/"$FILENAME"
git checkout res/GAMEHELP/"$FILENAME"
git checkout res/TITLE.HGR.UNPACKED/"$FILENAME"
git checkout res/TITLE.HGR/"$FILENAME"
git checkout res/dsk/"$DISKNAME"

FILENAME="COMMANDO"
DISKNAME="commando PRODOS (san inc pack).po"
git checkout res/ACTION.HGR.UNCOMPRESSED/"$FILENAME"
git checkout res/ACTION.HGR/"$FILENAME"
git checkout res/ARTWORK.SHR.SCORES/"$FILENAME"
git checkout res/ARTWORK.SHR.UNCOMPRESSED/"$FILENAME"
git checkout res/ARTWORK.SHR/"$FILENAME"
git checkout res/ATTRACT/"$FILENAME"
git checkout res/GAMEHELP/"$FILENAME"
git checkout res/TITLE.HGR.UNPACKED/"$FILENAME"
git checkout res/TITLE.HGR/"$FILENAME"
git checkout res/dsk/"$DISKNAME"


FILENAME="GORGON"
DISKNAME=""
git checkout res/ACTION.HGR.UNCOMPRESSED/"$FILENAME"
git checkout res/ACTION.HGR/"$FILENAME"
git checkout res/ARTWORK.SHR.SCORES/"$FILENAME"
git checkout res/ARTWORK.SHR.UNCOMPRESSED/"$FILENAME"
git checkout res/ARTWORK.SHR/"$FILENAME"
git checkout res/ATTRACT/"$FILENAME"
git checkout res/GAMEHELP/"$FILENAME"
git checkout res/TITLE.HGR.UNPACKED/"$FILENAME"
git checkout res/TITLE.HGR/"$FILENAME"
git checkout res/dsk/"$DISKNAME"


APPLE.PANIC
AZTEC
BATTLEZONE
CW
CENTIPEDE
CHOPLIFTER
CONAN
DEFENDER
DIG.DUG
GALAXIAN
GHOSTBUSTERS
GORGON
H.E.R.O
HARD.HAT.MACK
JOUST

   
KARATEKA
MINER.II
MOON.PATROL
MP
PACMAN
PR
PITFALL.II



FILENAME="ROBOTRON.2084"
DISKNAME="robotron 2084 13k file PRODOS (san inc pack).po"
git checkout res/ACTION.HGR.UNCOMPRESSED/"$FILENAME"
git checkout res/ACTION.HGR/"$FILENAME"
git checkout res/ARTWORK.SHR.SCORES/"$FILENAME"
git checkout res/ARTWORK.SHR.UNCOMPRESSED/"$FILENAME"
git checkout res/ARTWORK.SHR/"$FILENAME"
git checkout res/ATTRACT/"$FILENAME"
git checkout res/GAMEHELP/"$FILENAME"
git checkout res/TITLE.HGR.UNPACKED/"$FILENAME"
git checkout res/TITLE.HGR/"$FILENAME"
git checkout res/dsk/"$DISKNAME"


FILENAME="STARGATE"
DISKNAME=""
git checkout res/ACTION.HGR.UNCOMPRESSED/"$FILENAME"
git checkout res/ACTION.HGR/"$FILENAME"
git checkout res/ARTWORK.SHR.SCORES/"$FILENAME"
git checkout res/ARTWORK.SHR.UNCOMPRESSED/"$FILENAME"
git checkout res/ARTWORK.SHR/"$FILENAME"
git checkout res/ATTRACT/"$FILENAME"
git checkout res/GAMEHELP/"$FILENAME"
git checkout res/TITLE.HGR.UNPACKED/"$FILENAME"
git checkout res/TITLE.HGR/"$FILENAME"
git checkout res/dsk/"$DISKNAME"


FILENAME="TIME.TUNNELS"
DISKNAME="res/dsk/time tunnels 12k file PRODOS (san inc pack).po"
git checkout res/ACTION.HGR.UNCOMPRESSED/"$FILENAME"
git checkout res/ACTION.HGR/"$FILENAME"
git checkout res/ARTWORK.SHR.SCORES/"$FILENAME"
git checkout res/ARTWORK.SHR.UNCOMPRESSED/"$FILENAME"
git checkout res/ARTWORK.SHR/"$FILENAME"
git checkout res/ATTRACT/"$FILENAME"
git checkout res/GAMEHELP/"$FILENAME"
git checkout res/TITLE.HGR.UNPACKED/"$FILENAME"
git checkout res/TITLE.HGR/"$FILENAME"
git checkout res/dsk/"$DISKNAME"

FILENAME=""
DISKNAME=""
git checkout res/ACTION.HGR.UNCOMPRESSED/"$FILENAME"
git checkout res/ACTION.HGR/"$FILENAME"
git checkout res/ARTWORK.SHR.SCORES/"$FILENAME"
git checkout res/ARTWORK.SHR.UNCOMPRESSED/"$FILENAME"
git checkout res/ARTWORK.SHR/"$FILENAME"
git checkout res/ATTRACT/"$FILENAME"
git checkout res/GAMEHELP/"$FILENAME"
git checkout res/TITLE.HGR.UNPACKED/"$FILENAME"
git checkout res/TITLE.HGR/"$FILENAME"
git checkout res/dsk/"$DISKNAME"




# Notify the user
if [ $? -eq 0 ]; then
    echo "File '$FILENAME' has been successfully checked out."
else
    echo "Failed to checkout the file. Please check the filename and repository details."
fi
